---
title: "Submit_kaggle"
author: "Etienne Rolland"
date: "04/05/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Submission

Notebook to load a model, made the predictions on the test set and create the submissions for kaggle.


## Set up

```{r}
library(tidyverse)
library(keras)
library(tensorflow)
library(reticulate)
```


```{r}
use_python("/usr/bin/python3.5", required = TRUE)
tf <- tensorflow::tf
sess <- tf$Session()
```

```{r}
image_path<-'plant-pathology-2020-fgvc7/images/'
```

```{r}
#reticulate::virtualenv_install(packages="pandas") 
```

```{r}
keras::use_implementation("keras")
keras::use_backend("tensorflow")

```

```{r}
reticulate::py_config()
```


## Loading model

Last update of the Rmd doc Fine-tuning save only weights :

```{r}
conv_base <- application_resnet50(weights = 'imagenet', include_top = FALSE, input_shape = c(448, 448, 3))
```

```{r}
unfreeze_weights(conv_base, from="res3a_branch2a")
```


```{r}
model <- keras_model_sequential() %>% 
        conv_base %>% 
        layer_global_max_pooling_2d() %>% 
        layer_batch_normalization() %>%
        layer_dropout(rate=0.5) %>%
        layer_dense(units=4, activation="softmax")
```

```{r}
model
```

```{r}
checkpoint_dir <- "layer_3_models"

model %>% load_model_weights_hdf5(
  file.path(checkpoint_dir,"Resnet50_res3a_04.hdf5")
)
```


## Test set

```{r}
test<-readr::read_csv('plant-pathology-2020-fgvc7//test.csv')
test$image_id <- paste0(test$image_id, ".jpg")
head(test)
```

```{r}
image_path<-'plant-pathology-2020-fgvc7/images/'
```

With shuffle = FALSE to not mix images and got the right order in the predictions.

```{r}
test_generator <- flow_images_from_dataframe(dataframe = test, 
                                              directory = image_path,
                                              class_mode = NULL,
                                              x_col = "image_id",
                                              y_col = NULL,
                                              target_size = c(448, 448),
                                              shuffle = FALSE,
                                              batch_size=1)

```

```{r}
num_test_images<-1821

```


```{r}
pred <- model %>% predict_generator(test_generator, steps=num_test_images)
```


```{r}
head(pred)
```

```{r}
sample_submission<-read.csv("plant-pathology-2020-fgvc7/sample_submission.csv")
```

```{r}
pred<-as.data.frame(cbind("id", pred))
colnames(pred)<-colnames(sample_submission)
head(pred)
```

```{r}
pred[,1]<-gsub(".jpg","",test$image_id)
head(pred)
```

```{r}
write.csv(pred, file='submission_resnet_layer_3.csv', row.names=FALSE, quote=FALSE)
```





















